//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
namespace Game_Server.DBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBService.ITexasHoldemDB")]
    public interface ITexasHoldemDB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/Register", ReplyAction="http://tempuri.org/ITexasHoldemDB/RegisterResponse")]
        bool Register(string f_Name, string l_name, string userName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/Login", ReplyAction="http://tempuri.org/ITexasHoldemDB/LoginResponse")]
        TexasHoldemDBWCF.Player Login(string userName, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/CheckIfExist", ReplyAction="http://tempuri.org/ITexasHoldemDB/CheckIfExistResponse")]
        bool CheckIfExist(string inTable, string toSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/CreateTable", ReplyAction="http://tempuri.org/ITexasHoldemDB/CreateTableResponse")]
        int CreateTable(string name, int minAmountToEnter, int smallBlind, int bigBlind, int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/DeleteTable", ReplyAction="http://tempuri.org/ITexasHoldemDB/DeleteTableResponse")]
        bool DeleteTable(int tableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/GetId", ReplyAction="http://tempuri.org/ITexasHoldemDB/GetIdResponse")]
        int GetId(string fromTable, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/GetAllGamesTables", ReplyAction="http://tempuri.org/ITexasHoldemDB/GetAllGamesTablesResponse")]
        List<TexasHoldemDBWCF.Table> GetAllGamesTables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/JoinToTable", ReplyAction="http://tempuri.org/ITexasHoldemDB/JoinToTableResponse")]
        bool JoinToTable(int tableId, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/LeaveTable", ReplyAction="http://tempuri.org/ITexasHoldemDB/LeaveTableResponse")]
        void LeaveTable(int tableId, int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/GetPlayerInfo", ReplyAction="http://tempuri.org/ITexasHoldemDB/GetPlayerInfoResponse")]
        TexasHoldemDBWCF.Player GetPlayerInfo(int playerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITexasHoldemDB/UpdateMoney", ReplyAction="http://tempuri.org/ITexasHoldemDB/UpdateMoneyResponse")]
        void UpdateMoney(int playerId, int newAmount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITexasHoldemDBChannel : Game_Server.DBService.ITexasHoldemDB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TexasHoldemDBClient : System.ServiceModel.ClientBase<Game_Server.DBService.ITexasHoldemDB>, Game_Server.DBService.ITexasHoldemDB {
        
        public TexasHoldemDBClient() {
        }
        
        public TexasHoldemDBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TexasHoldemDBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TexasHoldemDBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TexasHoldemDBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Register(string f_Name, string l_name, string userName, string Password) {
            return base.Channel.Register(f_Name, l_name, userName, Password);
        }
        
        public TexasHoldemDBWCF.Player Login(string userName, string pwd) {
            return base.Channel.Login(userName, pwd);
        }
        
        public bool CheckIfExist(string inTable, string toSearch) {
            return base.Channel.CheckIfExist(inTable, toSearch);
        }
        
        public int CreateTable(string name, int minAmountToEnter, int smallBlind, int bigBlind, int adminId) {
            return base.Channel.CreateTable(name, minAmountToEnter, smallBlind, bigBlind, adminId);
        }
        
        public bool DeleteTable(int tableId) {
            return base.Channel.DeleteTable(tableId);
        }
        
        public int GetId(string fromTable, string tableName) {
            return base.Channel.GetId(fromTable, tableName);
        }

        public List<TexasHoldemDBWCF.Table> GetAllGamesTables()
        {
            return base.Channel.GetAllGamesTables();
        }
        
        public bool JoinToTable(int tableId, int playerId) {
            return base.Channel.JoinToTable(tableId, playerId);
        }
        
        public void LeaveTable(int tableId, int playerId) {
            base.Channel.LeaveTable(tableId, playerId);
        }
        
        public TexasHoldemDBWCF.Player GetPlayerInfo(int playerId) {
            return base.Channel.GetPlayerInfo(playerId);
        }
        
        public void UpdateMoney(int playerId, int newAmount) {
            base.Channel.UpdateMoney(playerId, newAmount);
        }
    }
}
